# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nick Chua 
title_separator: "|"
subtitle: Penetration Testing & CTF write-ups
name: "Nick Chua"
email: nickchua2205@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My personal website featuring Penetration Testing and Capture the Flag (CTF) write-ups. 
  I also share software engineering problems and related projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nickchua.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: "nickczh/nickchua"
teaser: /assets/images/teaser1.jpeg
logo: 
github_username:  nickczh

# Custom Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist

paginate: 5 # amount of posts to show
paginate_path: /page:num/
locale: "en-US"
search: true
breadcrumbs: true
date_format: "%d %B %Y"
permalink: none

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

defaults:
  # _foo
  - scope:
      path: ""
      type: foo
    values:
      layout: single

author:
  name     : "Nick Chua"
  avatar   : "/assets/images/avatar.jpeg"
  bio      : "Penetration Tester and Software Engineer"
  location : "Singapore"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
